### ISSUE TITLE
Provide a Kubernetes enricher

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.observability#19]
Provide a Kubernetes enricher that automatically adds information about:
- Namespace
- Name of node
- Name of pod

This will be based on environment variables that are added to deployments, similar to the following:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  labels:
          [... REDACTED ...]
spec:
  replicas: 2
  selector:
    matchLabels:
        app.kubernetes.io/name: demo-app
        app.kubernetes.io/instance: instance
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-app
        app.kubernetes.io/instance: instance
    spec:
      containers:
        - name: api
          [... REDACTED ...]
          env:
          - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: KUBERNETES_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
```

A sample by Tom will be provided as a starting point.
